//
//  SearchItemsWorkerTests.swift
//  AppleSearcher
//
//  Created by andrey on 31/01/16.
//  Copyright (c) 2016 AndreyLebedev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import AppleSearcher
import XCTest

class SearchItemsWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: SearchItemsWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupSearchItemsWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSearchItemsWorker()
  {
    sut = SearchItemsWorker(itemsStore: ItemsDataStoreSpy())
  }
  
  // MARK: Test doubles
  
  class ItemsDataStoreSpy: ItemsDataAPI { //temporary
    
    var fetchItemsCalled = false
    
    override func fetchItems(request: SearchItems_FetchItems_Request, completionHandler: (items: [Item], error: ItemsStoreError?) -> Void) {
      fetchItemsCalled = true
      let oneSecond = dispatch_time(dispatch_time_t(DISPATCH_TIME_NOW), 1 * Int64(NSEC_PER_SEC))
      dispatch_after(oneSecond, dispatch_get_main_queue()) { () -> Void in
        completionHandler(items: [], error: nil)
      }
    }
  }
  
  // MARK: Tests
  
  func testFetchItemsShouldReturnListOfItems() {
    // Given
    let itemDataStoreSpy = sut.itemsStore as! ItemsDataStoreSpy
    let request = SearchItems_FetchItems_Request(searchString:"Red", offset: 20, itemsInRequest: 20, language: "us_en")
    
    // When
    let expectation = expectationWithDescription("Wait for the fecth items result")
    sut.fetchItems(request) { (items, error) -> Void in
      expectation.fulfill()
    }
    
    // Then
    XCTAssertTrue(itemDataStoreSpy.fetchItemsCalled, "Calling fetchItems() should ask itemData store for a list of items")
    waitForExpectationsWithTimeout(1.1) { (error: NSError?) -> Void in
      XCTAssertTrue(true, "Calling fechItems should result completion handler being called")
    }
  }
}
