//
//  SearchItemsWorker.swift
//  AppleSearcher
//
//  Created by andrey on 31/01/16.
//  Copyright (c) 2016 AndreyLebedev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SearchItemsWorker
{
  var itemsStore: SearchItemsStoreProtocol
  
  init(itemsStore: SearchItemsStoreProtocol) {
    self.itemsStore = itemsStore
  }
  
  func fetchItems(searchString: String, completionHandler: (items: [Item]) -> Void) {
    itemsStore.fetchItems(searchString) { (items) -> Void in
      do {
        let items = try items()
        completionHandler(items: items)
      } catch {
        completionHandler(items: [])
      }
    }
  }
}

protocol SearchItemsStoreProtocol {
  func fetchItems(searchString: String, completionHandler: (items: () throws -> [Item]) -> Void)
}



